version: '3'
volumes:
  node_modules:
  emptyDockerDir:
networks:
  app_network:
services:
  traefik:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app_network
  app:
    restart: always
    build:
      context: .
    command: bash -c "node ./dist/api/App.server.js  -p 8080"
    #
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - 'traefik.protocol=http'
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://redis:6379
      - APP_DOMAIN=${APP_DOMAIN}
      - GIT_TAG=${GIT_TAG}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_URL=${GIT_URL}
    #      - CHOKIDAR_USEPOLLING=true
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    expose:
      - "8080"
    networks:
      - app_network
  mongodb:
    image: mongo
    restart: always
    command: --quiet
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ../../docker-data/mongodb:/data
    expose:
      - 27017
    networks:
      - app_network
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    expose:
      - 6379
    networks:
      - app_network
    volumes:
      - ../../docker-data/redis-data:/data