version: '3'
volumes:
  node_modules:
  emptyDockerDir:
networks:
  app_network:
services:
  traefik:
    image: "traefik:v2.0.0"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app_network
  app:
    restart: always
    build:
      context: .
    working_dir: /home/app
    #    command: bash -c "npm i&&wi-run :dev start"
    command: bash -c "${APP_RUN_BEFORE:-sleep 0}&&wi-run :${APP_MODE:-dev} start"
    #
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${APP_DOMAIN:-mamasound.localhost}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - 'traefik.protocol=http'
      - 'traefik.frontend.errors.network.status=["500-599"]'
      - 'traefik.frontend.errors.network.backend="error"'
      - 'traefik.frontend.errors.network.query="/index.html"'
    environment:
      - mongoUrl=mongodb://mongodb:27017
      - redisUrl=redis://redis:6379
      - APP_MODE=${APP_MODE:-dev}
      - APP_DOMAIN=${APP_DOMAIN:-mamasound.localhost}
    #      - CHOKIDAR_USEPOLLING=true
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    volumes:
      - ../..:/home/app
      - node_modules:/home/app/node_modules
      - ../../dump:/home/app/dump
    expose:
      - "8080"
    ports:
      - "${APP_DOCKER_DEBUG_PORT:-9229}:9229"
#      - "9090:9090"
    networks:
      - app_network
  error:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./500s:/usr/share/nginx/html:ro
    labels:
      - "traefik.backend=error"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:error.localhost"
      - "traefik.enable=true"
  mongodb:
    image: mongo
    restart: always
    command: --quiet
    environment:
      - MONGO_DATA_DIR=/data/mongodb
    volumes:
      - ../../docker-data/mongodb:/data
    expose:
      - 27017
    #    ports:
    #      - "27017"
    networks:
      - app_network
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    expose:
      - 6379
    networks:
      - app_network
    volumes:
      - ../../docker-data/redis-data:/data